[package]
name = "budget_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.33"
diesel = { version = "2.1.4", features = ["postgres"] }
dotenvy = "0.15.7"
